root -l -b -q 'fitResolandScale.C+(0)'
root -l -b -q 'fitResolandScale.C+(1)'
#root -l -b -q 'fitResolandScale.C+(2)'
#root -l -b -q 'fitResolandScale.C+(3)'
root -l -b -q 'fitResolandScale.C+(4)'
root -l -b -q 'fitResolandScale.C+(5)'
root -l -b -q 'fitResolandScale.C+(6)'
root -l -b -q 'fitResolandScale.C+(7)'
